Fix update machine
This change fixes the following error "Internal Server Error: 'Model'
object has no attribute 'isVirtualMachineType'".  In addtion unit
tests have been added to exersise the code path.

Change-Id: I75f3d551f34cbbb7f13cca83f5979a6367c0f776
Reviewed-by: Gabor Gombas <Gabor.Gombas@morganstanley.com>